# Generated by Django 4.2.3 on 2023-07-24 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Maid Request', 'Maid Request'), ('Technician Request', 'Technician Request'), ('Amenity Request', 'Amenity Request')])),
                ('defect_type', models.CharField(blank=True, choices=[('Electricity', 'Electricity'), ('Air Con', 'Air Con'), ('Plumbing', 'Plumbing'), ('Internet', 'Internet')], null=True)),
                ('amenity_type', models.CharField(blank=True, choices=[('Soap', 'Soap'), ('Towel', 'Towel'), ('Shower Cap', 'Shower Cap'), ('Razor', 'Razor')], null=True)),
                ('amenity_qty', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Created')),
                ('description', models.CharField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.room')),
            ],
        ),
    ]
